### ISSUE TITLE
Add code_of_conduct.md to the checked items. 

### ISSUE THREAD

**Issue by gedankenstuecke** [onyb/repomixer#4]
The title already says it all, but I think it would be cool to add this one to the checks as well. Could maybe even link to some generators/tips if not found?

**Comment by Ishub** [comment]
I think that is a nice idea to add that up too! Thanks for the heads up :)

**Comment by gedankenstuecke** [comment]
thanks, I added a quick solution to my PR. :smile: :fireworks:

**Comment by gedankenstuecke** [comment]
Thanks! :+1:
